### ISSUE TITLE
Read the same QRCode more than once

### ISSUE THREAD

**Issue by tiagosteil** [RonnyWeiss/APEX-QR-Code-Scanner#1]
Hi !

First of all, I would like to say that your plugin is **very** good! You did a great job and I believe it will help a lot of people, especially the APEX community. :smile: 

Now, I need your help with my situation. I configured the plugin in my app and it is running 100%! But it has a behavior that I need to change.

When I read a QRCode the plugin returns its code and I can handle the code read in my app, however, it is not possible to re-read the same code ... How can I do this?

I need to be able to read the same code more than once, can you help me or tell me what I need to do for this?

**Comment by RonnyWeiss** [comment]
Sorry for late answer. I just updated the QR Code Plug-in in Version 1.4 with the possibility to Control the Scanner. You can fire Events on the QR Region:

$("#qrscanner_region").trigger("scannerPause"); => Pause the scanner 

$("#qrscanner_region").trigger("scannerPlay"); => Restart the scanner from pause

$("#qrscanner_region").trigger("resetValue"); => Reset value to rescan the same QR Code if needed

So I think your request if solved, correct me if not and have a nice Sunday.
