### ISSUE TITLE
lately, reply about mirror phenomenon 

### ISSUE THREAD

**Issue by yain3746** [RonnyWeiss/APEX-QR-Code-Scanner#10]
sorry for lately reply.
I have picture about it.
whenever, scanner working on rear camera. there is no problem. But, when it turn to front camera. there is reverse about left and right.
when I stretch my right arm at front camera, camera screen show left side I stretch. 
so, we try to use front camera, it make little confuse. 

how can I upload or send picture?

**Comment by yain3746** [comment]
![rear_Camera_pricture](https://user-images.githubusercontent.com/73065517/101479750-0bc0e280-3996-11eb-8ee1-259469c0c89d.png)
this is rear side camera picture
![front_Camera_picture](https://user-images.githubusercontent.com/73065517/101479757-0d8aa600-3996-11eb-9bd2-b34f32520375.png)
this is front side camera picture

front camera works like rear side camera. there for there is happening left and right reverse.

**Comment by RonnyWeiss** [comment]
did you check latest release? there you can set by option the mirroring of the camera.

**Comment by RonnyWeiss** [comment]
no reaction so will close the issue
