### ISSUE TITLE
QR in apex Arabic application 

### ISSUE THREAD

**Issue by ahmad-fathy-1981** [RonnyWeiss/APEX-QR-Code-Scanner#11]
in apex arabic application QR return invoice number with Arabic context 

if invoice number = 2000000028

it return in Arabic version application  ٢٠٠٠٠٠٠٠٢٨

so all the search will not see that invoice

**Comment by RonnyWeiss** [comment]
is is also when using string?

**Comment by RonnyWeiss** [comment]
Tried it in my sample app and everything works fine. Can you please give me more details?

**Comment by ahmad-fathy-1981** [comment]
try this application 20.2 v


you can see what I mean

login with Arabic lang then scan any code will see Arabic number returned in text


Ahmad Fathy Radwan
Oracle Financial Consultant
Oracle Technical Consultant
Oracle Business Intelligence Consultant
Oracle Application Development Framework Developer
Oracle Apex Developer
Oracle (Forms Report) Developer
Mobile:  +966563481733
ahmad_fathy@outlook.com

________________________________

**Comment by RonnyWeiss** [comment]
I tried exctly this and it works. Do you have an account on apex.oracle.com? and could you please download my sample app and try it again?
