### ISSUE TITLE
Long number strange behavior

### ISSUE THREAD

**Issue by adambadge** [RonnyWeiss/APEX-QR-Code-Scanner#12]
Amazing plugin thank you! I am experiencing strange behavior with longer numbers in sequential order I was hoping you could suggest a fix for?

When I scan the following QR codes in order everything works fine:
QR 1 - 542099931871011
QR 2 - 54209993187108
QR 3 - 542099931871010

Everything works as expected but when I scan QR 1 then QR 3 the page item does not update.
I suspect this could be a truncating issue because the QR 1 and QR 3 are in sequential order?

I am currently playing around with number conversation and triggering a value reset after every scan as work around but wondering if there is a more permanent solution?

Thank you again for your amazing contributions.

**Comment by adambadge** [comment]
Reading some of the closed issues this appears to be related to QR 1 and QR 3 being of the same length. Is there a solution to this? They are in fact different values but just happen to be of the same length.

**Comment by RonnyWeiss** [comment]
Hello

Thank you for the issue! Ich checked the code and will change it. Currently there's only a length check and I will replace it with string compare. Don't know why only checkin length! Update will be published this evening in Version 1.5.1.0! 

Have a nice day

Kind regards

Ronny

**Comment by adambadge** [comment]
Thank you Ronny! Very much appreciated. Keep up the great work :)
