### ISSUE TITLE
QR Scanner stops scanning on Iphone (Safari/Chrome)

### ISSUE THREAD

**Issue by sietse-pp** [RonnyWeiss/APEX-QR-Code-Scanner#13]
Hi Ronny, 
Thanks for the plugin. We're using it to scan QR codes on mobile phones and this works great on Android.
We have one issue however: after some scans on an Iphone (6-10 scans often) it stops recognizing QR codes.

The situation:
1. QR scanner plugin sets an item when a QR code is scanned.
2. On change of this item, a message is shown and after some delay (setTimeout), `$("#qr_scanner").trigger("resetValue");` is called.
3. Scanning the same code or a different one goes well for about 6-10 tries
4. The camera is still working but no red border appears around QR codes anymore. It doesn't seem to recognize any QR codes at this point.

Any idea what we can do about this? 

Thanks!

**Comment by RonnyWeiss** [comment]
Which version are you using?

**Comment by RonnyWeiss** [comment]
Do you have any errors on console in console of safari?

**Comment by sietse-pp** [comment]
Thanks for replying.
We were using version 1.5! But we were in a hurry and ended up using the Javascript library Html5-QRCode.
