### ISSUE TITLE
Code scanner region does not show in iOS

### ISSUE THREAD

**Issue by mathiasmaciel97** [RonnyWeiss/APEX-QR-Code-Scanner#15]
I set region as correspond but with Inline Dialog as template on Modal Dialog page. It asks for camera permission but when I allow it nothing happens. 
I define sub region to advertise user that it should allow browser to access device camera.

![EFCCD178-B783-4E29-BBF0-6A45F39126B9](https://user-images.githubusercontent.com/39440207/190017490-775c3c27-c9b8-4128-9de0-f57b1d1eeec4.jpeg)

**Comment by mathiasmaciel97** [comment]
After several attempts, I noticed that this behavior is not related just Safari but any browser in iOS. It seems like the region does not render properly and you can not see it but it is there. It works because if you point correctly to QR code, it scans it.

**Comment by RonnyWeiss** [comment]
Hey there, 
Thank you for your ticket. Could you please provide english Screenshots, I cannot work with these ones!
Does it work when you use the plug-in in a normal page?
When you set in custome attributes of the qr-code region the following: style="height:400px;" does this work then in modal dialogs?

**Comment by RonnyWeiss** [comment]
I have no apple device , but I tested the plug-in on a normal page and on a modal dialog with my sample app on apex.oracle.com in a BrowserStack iOS Real Device. So maybe the problem is in your app. could you please provide me a sample app on apex.oracle.com. So I can reproduce the issue?

**Comment by mathiasmaciel97** [comment]
It works fine in Normal Page Mode. As I mentioned, it is not strictly related to functionality but behavior of camera preview that you can not see. There was not changes by setting that attribute.
Current scenario: Inline Dialog template region for QR scanner in Modal Page Mode.
I created a new [app](https://apex.oracle.com/pls/apex/r/mathias_maciel/demo-qr/) with similar settings on [https://apex.oracle.com/](https://apex.oracle.com/). Feel free to login and test it.
Here are your credentials:
- Username: ronny
- Password: Ronny2022**!

**Comment by RonnyWeiss** [comment]
Hi there, sorry for late replay but what you are doing cannot work on ios. Camera can only be initialized when visible on iOS so this cannot work! You need to open the Scanner in a visible region on page load not in a hidden inline dialog!

**Comment by mathiasmaciel97** [comment]
So, does this behavior is just for iOS devices?

**Comment by RonnyWeiss** [comment]
Yes that's only for iOS devices. I think Android is not so restricted. But it makes sense to me what Apple is doing for privacy reasons
