### ISSUE TITLE
Not data found

### ISSUE THREAD

**Issue by Alejoald94** [RonnyWeiss/APEX-QR-Code-Scanner#16]
I have issues when I try to save what the qr scann read, that error appear! help!
![image](https://user-images.githubusercontent.com/107277809/196956011-375a7a27-52f5-4a0e-9535-44fa3c8280d3.png)
![image](https://user-images.githubusercontent.com/107277809/196956121-4f48b551-9b73-4539-98c9-702844441a80.png)

**Comment by RonnyWeiss** [comment]
Hi there,could you please provide a sample app on apex.oracle.com? So that I have a change to reproduce the issue? What APEX Version are you using?

**Comment by RonnyWeiss** [comment]
No response since weeks
