### ISSUE TITLE
Problem with scanning similar QR codes

### ISSUE THREAD

**Issue by Yah0000** [RonnyWeiss/APEX-QR-Code-Scanner#2]
I try to scan few QR Code one after another.
It works when the QR Code are completely different, but when i try to scan similar QR Code the APEX item connected with plugin no change. 
The same when I use "Execute JavaScript" mode with "alert". There is no effect when QR codes are simmilar. 

My similar QR codes lead to URL:
```
http://localhost/ords11/f?p=TEST:GET:::::ITEM:12345
http://localhost/ords11/f?p=TEST:GET:::::ITEM:12346
```

Library recognise both codes but only when I refresh page.
Have you any idea what is the problem?

QR code works well when I use library sample page: https://cozmo.github.io/jsQR/

**Comment by tiagosteil** [comment]
Hi,

This is the same problem I have, described at: https://github.com/RonnyWeiss/APEX-QR-Code-Scanner/issues/1

In my case, I edited the file "js/script.js" and removed the if command from line 178.

`if (bStr.length! = code.data.length) {`

I hope this solve for you too

**Comment by Yah0000** [comment]
Thanks a lot!

I change to: 
`if (bStr != code.data) {`
Now it works as I want. I think it should be change in repo.
