### ISSUE TITLE
Scan data matrix code

### ISSUE THREAD

**Issue by millo025** [RonnyWeiss/APEX-QR-Code-Scanner#4]
Hello, i was testing the plugin and i have trouble reading the datamatrix codes, is any chance to plugin do that?

**Comment by RonnyWeiss** [comment]
Can you please send me the code?

**Comment by millo025** [comment]
Good day Ronny

Thanks, this is an example of couple of data matrix codes, one is generic
the other one is the real code i must read on my app.

**Comment by RonnyWeiss** [comment]
Hello

Where are the files? maybe they get lost when you send email please upload them on github.

KR Ronny

**Comment by millo025** [comment]
[image: dm code.png]
[image: datamatrix-code-multiple-matrix.png]

**Comment by RonnyWeiss** [comment]
The images where not attached please try again

**Comment by millo025** [comment]
Hi Ronny

Is rare, i attached a word file with the images and a zip.

Greetings

**Comment by RonnyWeiss** [comment]
![screenshot](https://user-images.githubusercontent.com/30749177/77342634-c5a4ef80-6d30-11ea-8d96-726938cf7337.gif)
Do you see the image in this post? Then please login to github web and click below write field when comment "Attach files by dragging..." and upload images. Hope they will not be filtered

**Comment by millo025** [comment]
[datamatrix-code-multiple-matrix.zip](https://github.com/RonnyWeiss/APEX-QR-Code-Scanner/files/4370986/datamatrix-code-multiple-matrix.zip)
<img width="103" alt="dm code" src="https://user-images.githubusercontent.com/57270485/77344927-8313f080-6cf9-11ea-8de8-5533befc91f2.png">
https://www.codigos-qr.com/wp-content/uploads/2018/06/datamatrix-code-multiple-matrix.png

**Comment by RonnyWeiss** [comment]
Ah now it's working. This kind of matrix codes I do not support. I only support QR-Codes. So maybe you can user another liabry for scanning code e.g. https://github.com/zxing-js/library. But with my plug-in you can only scan qr codes

**Comment by millo025** [comment]
i got it Ronny, thank you so well

**Comment by RonnyWeiss** [comment]
No Problem
