### ISSUE TITLE
Camera in Chrome Mobile can't open.

### ISSUE THREAD

**Issue by phucph-cntt** [RonnyWeiss/APEX-QR-Code-Scanner#5]
Hi Ronny,
Thank for your plugin. 
I used it in my Oracle Apex App and it's good for browser in PC.
I use Chrome Browser on Mobile, I can open camera in https://apex.oracle.com/pls/apex/f?p=103428:20:704392563107006:::::
But i can't open it in my App; browser don't open notification Alow camera.
Can you help me. Thank you very much.
Best Rgds.

**Comment by RonnyWeiss** [comment]
Has the browser access top the camera?

**Comment by RonnyWeiss** [comment]
Did you check my latest version of this plug-in?

**Comment by RonnyWeiss** [comment]
Closed because no answer
