### ISSUE TITLE
Can't scan multiple code ?

### ISSUE THREAD

**Issue by ThomasCarltonInPerson** [RonnyWeiss/APEX-QR-Code-Scanner#6]
Hi, 

Thank you for your awesome plugin.

I'm trying to scan several codes , but the plugin scans only the first one. The other ones are detected in the video streaming but the scan trigger is not working.

After each scan I'm running the following commands : 

`alert(scannedValue);
$("#scannerregion").trigger("scannerPause");
$("#scannerregion").trigger("scannerPlay");
$("#scannerregion").trigger("resetValue");
`

This code shows the scanned value only once. No JS error is raised.

Am I missing something please ?

thanks.
Cheerss,

**Comment by RonnyWeiss** [comment]
Hello

Ok I tried it in my sample app and everything is working? why do you pause the scanner? when you want to rescan the same code then you just need to trigger ResetValue. My thought where like that: 

- you scan a code
- then fire a dynamic action with pl/sql which does some stuff
- reset the scanner or scan another qr code :-)

What is your use case?

kind regards

Ronny

**Comment by ThomasCarltonInPerson** [comment]
I have tried several things and come up with the following conclusion : 

- If reset follows immediatly the scan : it works only once.
- If reset is executed after a small delay (for example 200ms) : it works several times

Here is an example with both cases : 
[https://apex.oracle.com/pls/apex/tataf12906/r/scanner-test/scanner](url)

**Wokspace :** tataf12906
**Email :** tataf12906@relrb.com
**Password :** R0ONq6pC18hUrX7

My problem is solved now since I'm waiting 200ms before reseting the scanner. But I'm putting this here in case some gets the same problem.

Thanks again for your awesome plugin :) !

**Comment by RonnyWeiss** [comment]
Did you move the qer code away from scanner or is it always in front of the camera?

**Comment by RonnyWeiss** [comment]
No reaction so I will close issues
