### ISSUE TITLE
It's available to use this scanner in Android phone?

### ISSUE THREAD

**Issue by hilmi88** [RonnyWeiss/APEX-QR-Code-Scanner#7]
Hi,
First, I want to say thank you for your QR-Code-Scanner, it help me a lot and many things I can do with this. 

Before I want to ask 1 question, I would like to tell you, this QR-Code-Scanner working fine at any browser in Smart Phone.
When I convert my Apex Application into Android .apk, QR-Code-Scanner not working as well as I'm using at any browser in Smart Phone. 
For your information, I use this site `_https://gonative.io_` to convert my Apex Application.

My question is, it's any solution how to solve this issues?,and I need your advice for this issues. I hope you can respond ASAP. 

Thank you.

**Comment by RonnyWeiss** [comment]
Hello

Thank you for compliment. At first let me ask you you jsut did convert the app and then you tried it out and it was not working? Do you know some details about devloping android apps?

Kind regards

Ronny

**Comment by hilmi88** [comment]
Hello,

 

Thank you for your reply my issues,

 

1.	you just did convert the app and then you tried it out and it was not working?

*	Yes, I just convert the app, then I tried to download and install to my phone.
*	When I open at QR Scanner, it keep loading QR Scanner Region. When I test on browser it was fine, nothing problem. 

 

2.	Do you know some details about developing android apps? 

*	Not much I know about Developing Android Apps.
*	Did this QR Scanner need put some code of Android Apps?, if so, can you give me an advice how to do it.

 
………………………………………………………………………………………………………………..

Best regards:

Name : Wan Ahmad Hilmi 
Email : hilmi@ems.com.my

**Comment by RonnyWeiss** [comment]
Hello

But forget that this is so easy I developed some android apps natively and believe me if it would be so easy to develope native apps including api usage of camera then nobody would develope it natively! 

so without creating a manifest where you set usage of camera api and more this can't work!

Kind regards

Ronny

**Comment by RonnyWeiss** [comment]
No answer since one week
