### ISSUE TITLE
IOS can't run the camera to scan the QR_Code

### ISSUE THREAD

**Issue by AaronBear** [RonnyWeiss/APEX-QR-Code-Scanner#8]
This APEX-Plug you developed is so nice . I find that it works well in Android but in IOS by Wechat

**Comment by RonnyWeiss** [comment]
What do you mean in WeChat?

**Comment by RonnyWeiss** [comment]
Closed because no reaction and bug could not be reproduced! Please reopen the ticket if issue still exists

**Comment by RonnyWeiss** [comment]
fixed in Version 1.5
