### ISSUE TITLE
mirror phenomenon and doesn't work at new android os 

### ISSUE THREAD

**Issue by yain3746** [RonnyWeiss/APEX-QR-Code-Scanner#9]
dear developer.
I am happy to use your code during developing Apex application.
however, we found one phenomenon that may occured, the camera and vedio show mirror phenomenon.
I do not know how to overcome this phenomenon.
could you please how to solve this problem? 
I hope you to consider about this issue. 
regard you developer.

**Comment by RonnyWeiss** [comment]
Hello

Thank you for your issue. Do you have a screenshot of the problem? Because on my Android 10 Test Device it works perfectly

Kind regards

Ronny

**Comment by RonnyWeiss** [comment]
No reaction! Closed

**Comment by yain3746** [comment]
![front_Camera_picture](https://user-images.githubusercontent.com/73065517/101479600-c7cddd80-3995-11eb-81af-2686ece20515.png)
![rear_Camera_pricture](https://user-images.githubusercontent.com/73065517/101479603-c997a100-3995-11eb-9e37-64e1068a4602.png)
